#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.2.6.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  test_api_key: 123456

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: CI

# scripts to run before build
before_build:
  - nuget restore src\Bugsnag.Core\packages.config
  - nuget restore src\Bugsnag.Web\packages.config
  - nuget restore test\Bugsnag.Core.Test\packages.config