#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.2.6.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  test_api_key: 123456

#---------------------------------#
#       build configuration       #
#---------------------------------#

# scripts to run before build
build_script:
  ps: import-module ".\build\psake.psm1";invoke-psake ".\build\build.ps1"
  
# build script will run tests
test: off
  
#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
 
artifacts:
  # pushing entire folder as a zip archive
  - path: build\output\bin
    name: Bugsnag.$(APPVEYOR_BUILD_VERSION)
    type: zip
 
  # pushing all *.nupkg files in directory
  - path: build\output\*.nupkg
    name: Bugsnag.$(APPVEYOR_BUILD_VERSION)

