#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.2.6.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  test_api_key: 123456

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration:
  - Debug
  - Release
  - MonoRelease

# scripts to run before build
build_script:
  build/build.bat

