#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.2.6.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  test_api_key: 123456

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration:
  - Debug
  - Release

# scripts to run before build
before_build:
  nuget restore

after_build:
  - ps: . .\CodeAnalysis.ps1
  - ps: analyseCodeAnalysisResults ".\src\Bugsnag.Core\bin\Debug\Bugsnag.Core.dll.CodeAnalysisLog.xml"
  - ps: analyseCodeAnalysisResults ".\src\Bugsnag.Web\bin\Debug\Bugsnag.Web.dll.CodeAnalysisLog.xml"
  - ps: Push-AppveyorArtifact ".\src\Bugsnag.Core\obj\Debug\StyleCopViolations.xml" -FileName "Bugsnag.Core.StyleCopViolations.xml"
  - ps: Push-AppveyorArtifact ".\src\Bugsnag.Web\obj\Debug\StyleCopViolations.xml" -FileName "Bugsnag.Web.StyleCopViolations.xml"
